<?php

namespace App\Http;

use Illuminate\Support\Arr;

class BrandList
{
    private static $brands = [
        "Walter Zulauf and Rempel",
        "Boyle-Mills",
        "Daniel Haag and Kertzmann",
        "Jerde Kub and Smith",
        "Heaney Hand and Fay",
        "Padberg Gleichner and Dickens",
        "Reilly Hintz and Ernser",
        "Will Donnelly and Kulas",
        "Monahan-Kilback",
        "Kerluke-Murphy",
        "Stanton-Shanahan",
        "Hoeger Group",
        "Ernser-Olson",
        "Hand Group",
        "Balistreri LLC",
        "White and Sons",
        "Baumbach Vandervort and Marks",
        "Smith-Zboncak",
        "Bernhard Leffler and Fahey",
        "Jaskolski Group",
        "Lockman-Turcotte",
        "Mayer Smith and Schmitt",
        "Gutkowski Okuneva and Farrell",
        "Sipes PLC",
        "Kihn Mosciski and Mayer",
        "Ledner and Sons",
        "Becker Waters and Anderson",
        "Schmidt Runolfsson and Kshlerin",
        "Gislason Raynor and Koepp",
        "Satterfield Group",
        "Mraz PLC",
        "Will-Wintheiser",
        "Treutel-Moore",
        "McKenzie LLC",
        "Ruecker Ltd",
        "Johns-O'Reilly",
        "Stroman Ltd",
        "Dickens-McKenzie",
        "Kshlerin-Rosenbaum",
        "Littel-Murray",
        "Mosciski and Sons",
        "Hegmann-Sipes",
        "Rutherford-Gleason",
        "Daugherty-Goyette",
        "Price and Sons",
        "Sporer LLC",
        "McLaughlin-Lubowitz",
        "Renner-Dickens",
        "Schinner-Dare",
        "Kuhic PLC",
        "Koss Group",
        // "Rutherford and Sons",
        // "Abbott Paucek and Brown",
        // "Bernhard LLC",
        // "Nolan-Zboncak",
        // "Schowalter and Sons",
        // "Von King and Stroman",
        // "Quitzon-Cartwright",
        // "Schuppe-Monahan",
        // "Dach Ltd",
        // "Kunde Moore and Wolff",
        // "Johnston-VonRueden",
        // "VonRueden PLC",
        // "Nienow Dickens and Donnelly",
        // "McCullough Ltd",
        // "Barrows PLC",
        // "Keebler Berge and Stamm",
        // "Murphy Inc",
        // "Kunze LLC",
        // "Grady and Sons",
        // "Erdman Ltd",
        // "Stark Ltd",
        // "Anderson Group",
        // "Jacobson Lynch and Rosenbaum",
        // "Anderson Conn and Flatley",
        // "Ryan-Gibson",
        // "Nitzsche Inc",
        // "Donnelly Group",
        // "Considine and Sons",
        // "Parker Wolff and Leffler",
        // "Anderson PLC",
        // "Nicolas-Lang",
        // "Turcotte-Graham",
        // "Hettinger Ltd",
        // "Lubowitz Ltd",
        // "Kertzmann Inc",
        // "McClure-Stoltenberg",
        // "Hickle Mills and Krajcik",
        // "Herzog Feil and Rohan",
        // "Lebsack Ltd",
        // "Ankunding Inc",
        // "Walter Zulauf and Rempel",
        // "Boyle-Mills",
        // "Daniel Haag and Kertzmann",
        // "Jerde Kub and Smith",
        // "Heaney Hand and Fay",
        // "Padberg Gleichner and Dickens",
        // "Reilly Hintz and Ernser",
        // "Will Donnelly and Kulas",
        // "Monahan-Kilback",
        // "Kerluke-Murphy",
        // "Stanton-Shanahan",
        // "Hoeger Group",
        // "Ernser-Olson",
        // "Hand Group",
        // "Balistreri LLC",
        // "White and Sons",
        // "Baumbach Vandervort and Marks",
        // "Smith-Zboncak",
        // "Bernhard Leffler and Fahey",
        // "Jaskolski Group",
        // "Lockman-Turcotte",
        // "Mayer Smith and Schmitt",
        // "Gutkowski Okuneva and Farrell",
        // "Sipes PLC",
        // "Kihn Mosciski and Mayer",
        // "Ledner and Sons",
        // "Becker Waters and Anderson",
        // "Schmidt Runolfsson and Kshlerin",
        // "Gislason Raynor and Koepp",
        // "Satterfield Group",
        // "Mraz PLC",
        // "Will-Wintheiser",
        // "Treutel-Moore",
        // "McKenzie LLC",
        // "Ruecker Ltd",
        // "Johns-O'Reilly",
        // "Stroman Ltd",
        // "Dickens-McKenzie",
        // "Kshlerin-Rosenbaum",
        // "Littel-Murray",
        // "Mosciski and Sons",
        // "Hegmann-Sipes",
        // "Rutherford-Gleason",
        // "Daugherty-Goyette",
        // "Price and Sons",
        // "Sporer LLC",
        // "McLaughlin-Lubowitz",
        // "Renner-Dickens",
        // "Schinner-Dare",
        // "Kuhic PLC",
        // "Koss Group",
        // "Rutherford and Sons",
        // "Abbott Paucek and Brown",
        // "Bernhard LLC",
        // "Nolan-Zboncak",
        // "Schowalter and Sons",
        // "Von King and Stroman",
        // "Quitzon-Cartwright",
        // "Schuppe-Monahan",
        // "Dach Ltd",
        // "Kunde Moore and Wolff",
        // "Johnston-VonRueden",
        // "VonRueden PLC",
        // "Nienow Dickens and Donnelly",
        // "McCullough Ltd",
        // "Barrows PLC",
        // "Keebler Berge and Stamm",
        // "Murphy Inc",
        // "Kunze LLC",
        // "Grady and Sons",
        // "Erdman Ltd",
        // "Stark Ltd",
        // "Anderson Group",
        // "Jacobson Lynch and Rosenbaum",
        // "Anderson Conn and Flatley",
        // "Ryan-Gibson",
        // "Nitzsche Inc",
        // "Donnelly Group",
        // "Considine and Sons",
        // "Parker Wolff and Leffler",
        // "Anderson PLC",
        // "Nicolas-Lang",
        // "Turcotte-Graham",
        // "Hettinger Ltd",
        // "Lubowitz Ltd",
        // "Kertzmann Inc",
        // "McClure-Stoltenberg",
        // "Hickle Mills and Krajcik",
        // "Herzog Feil and Rohan",
        // "Lebsack Ltd",
        // "Ankunding Inc",
        // "Kessler-Haley",
        // "Wunsch Gorczany and Abshire",
        // "Feeney Metz and Funk",
        // "Kirlin and Sons",
        // "O'Connell Kautzer and Friesen",
        // "Littel and Sons",
        // "Lang and Sons",
        // "Medhurst Ltd",
        // "Pfeffer-Nader",
        // "Haag Inc",
        // "Macejkovic-Lesch",
        // "Braun Flatley and Johnson",
        // "Carter LLC",
        // "Treutel-Wehner",
        // "Bradtke PLC",
        // "Miller-Renner",
        // "Terry Gibson and Hane",
        // "Pfeffer Inc",
        // "Kuhic and Sons",
        // "Cremin Bauch and Kulas",
        // "Spencer Glover and Hermann",
        // "Sauer Hartmann and Leuschke",
        // "Greenfelder-Jacobs",
        // "Windler Stiedemann and Conn",
        // "Runolfsdottir Lowe and Murazik",
        // "Keeling Gottlieb and Fadel",
        // "Purdy Group",
        // "Rolfson-Harvey",
        // "Kulas Ratke and Kautzer",
        // "Feeney Inc",
        // "Harris and Sons",
        // "Rath-Ebert",
        // "Jenkins-Bartoletti",
        // "Collier PLC",
        // "Murphy-Gorczany",
        // "Johnston Bradtke and Swaniawski",
        // "Gusikowski Miller and Stokes",
        // "Ruecker-Boyle",
        // "Okuneva Ltd",
        // "Hamill-Bauch",
        // "Weimann-Botsford",
        // "Brekke-Rippin",
        // "Bayer Goodwin and Stark",
        // "Denesik-Marquardt",
        // "Runolfsdottir-Beer",
        // "Breitenberg Inc",
        // "Bode-Cole",
        // "Mann PLC",
        // "Brakus-Anderson",
        // "Rau-Conroy",
        // "Bode Farrell and Wolf",
        // "Beier Mitchell and Williamson",
        // "Schneider Bins and Wiegand",
        // "Gulgowski LLC",
        // "Rolfson-Mohr",
        // "Ondricka LLC",
        // "Kovacek Group",
        // "Torp LLC",
        // "Schulist-Koss",
        // "Rohan-Marks",
        // "Mitchell-Mitchell",
        // "Weber-Kreiger",
        // "Pagac Group",
        // "Waters Inc",
        // "Durgan-Swift",
        // "Runolfsdottir-Osinski",
        // "Sawayn Hyatt and Rippin",
        // "Howell Gibson and Will",
        // "White Ltd",
        // "Kuhlman-Powlowski",
        // "Nitzsche Parker and Grant",
        // "Cartwright-Johnson",
        // "Pfannerstill-Lowe",
        // "Gaylord Mertz and Jast",
        // "Parker Thiel and Ruecker",
        // "Bradtke Group",
        // "Dibbert Cummings and Thiel",
        // "Schmeler LLC",
        // "Steuber Inc",
        // "Rodriguez-Rohan",
        // "Wilderman PLC",
        // "Wunsch Inc",
        // "Bins Group",
        // "Kuhic Inc",
        // "Langosh-Jacobs",
        // "Wintheiser Wyman and Turcotte",
        // "Bahringer Dickinson and Pfeffer",
        // "Kris LLC",
        // "Smith-Thiel",
        // "Lueilwitz Ltd",
        // "Williamson PLC",
        // "Stark Ltd",
        // "Dickinson-Sipes",
        // "Pouros-Hayes",
        // "McDermott Zieme and McGlynn",
        // "Pagac Schoen and Ryan",
        // "Nienow Inc",
        // "Mann Group",
        // "Cronin-Runolfsdottir",
        // "Durgan Kuhic and Turner",
        // "Marvin Konopelski and Gulgowski",
        // "Hayes and Sons",
        // "Boyle Group",
        // "Hudson-Spinka",
        // "Reichel Inc",
        // "McKenzie Pacocha and Gleichner",
        // "Waelchi Group",
        // "Hilpert PLC",
        // "Bahringer VonRueden and Christiansen",
        // "Daugherty Maggio and Kuhlman",
        // "Goodwin PLC",
        // "Ortiz Blick and Connelly",
        // "Gulgowski Rath and Leffler",
        // "Schuster Altenwerth and Runolfsdottir",
        // "Deckow Skiles and Schmitt",
        // "Kuhlman Balistreri and Padberg",
        // "Kuhlman-Schimmel",
        // "Senger Erdman and Turcotte",
        // "Hill Ltd",
        // "Ryan PLC",
        // "Feil Witting and Steuber",
        // "Casper Haag and Leannon",
        // "King Group",
        // "Klocko Group",
        // "Altenwerth and Sons",
        // "Emmerich-Lebsack",
        // "Schroeder-O'Conner",
        // "Simonis PLC",
        // "Spencer-Keebler",
        // "Krajcik Inc",
        // "Hackett LLC",
        // "Raynor Turner and Klein",
        // "Corwin Hettinger and Waters",
        // "Lehner PLC",
        // "Parisian LLC",
        // "Orn PLC",
        // "Witting-Keeling",
        // "Kling LLC",
        // "Blanda LLC",
        // "Wolff-Rice",
        // "Nienow Wiegand and Kris",
        // "Leffler Kling and Ullrich",
        // "Reichel-Hand",
        // "Franecki Hyatt and Kautzer",
        // "Cartwright Kovacek and Botsford",
        // "Sporer Langworth and Romaguera",
        // "Ledner and Sons",
        // "Shields Inc",
        // "Rempel Goyette and Dickens",
        // "Gibson Deckow and Blanda",
        // "Shields Inc",
        // "Jacobson Swift and White",
        // "Heidenreich Ratke and Wunsch",
        // "Murray Muller and White",
        // "Fadel-Kuhic",
        // "Grimes Group",
        // "Klocko Wiegand and Larson",
        // "Bartoletti Hamill and Johnston",
        // "Koepp-Howe",
        // "Beier PLC",
        // "Kshlerin Group",
        // "Schulist-Corkery",
        // "Schmitt Inc",
        // "Lebsack-Osinski",
        // "Heller Inc",
        // "Heathcote Ltd",
        // "Champlin-King",
        // "Hills PLC",
        // "Gerlach Ltd",
        // "Farrell Dietrich and Hermann",
        // "Lowe-Lowe",
        // "Dare Jones and Stamm",
        // "Gislason Dietrich and Daniel",
        // "Hodkiewicz-Bayer",
        // "Muller Jacobson and Hegmann",
        // "Crist-Gottlieb",
        // "Volkman Group",
        // "Bechtelar-Moore",
        // "Moore-Rolfson",
        // "Kuhic Effertz and Blick",
        // "Cummings Wilkinson and Ziemann",
        // "O'Kon-Crona",
        // "Schowalter Inc",
        // "Renner Ltd",
        // "Pfeffer Group",
        // "Kling Carter and Cronin",
        // "Lemke Rath and Rodriguez",
        // "Rempel Cronin and Wiza",
        // "Schmidt and Sons",
        // "Rowe-Harber",
        // "Casper Rosenbaum and Brown",
        // "Crist Group",
        // "Schumm Klocko and Tromp",
        // "Huels-Johnson",
        // "Kautzer-Hudson",
        // "Wiza Armstrong and Trantow",
        // "Walsh Kuphal and Schroeder",
        // "Mitchell-Hayes",
        // "Lesch and Sons",
        // "DuBuque Wolf and Beatty",
        // "Beahan Wolff and Legros",
        // "Kertzmann Cremin and Langosh",
        // "Cummings and Sons",
        // "Howell LLC",
        // "Corkery and Sons",
        // "Ratke Bayer and Tromp",
        // "Treutel-Harber",
        // "Parisian-Mueller",
        // "Kessler-Koss",
        // "Von Inc",
        // "O'Keefe Inc",
        // "White Harvey and Gulgowski",
        // "Brown-Carroll",
        // "Pollich PLC",
        // "Ratke-Breitenberg",
        // "O'Conner Inc",
        // "Lakin Heaney and Mante",
        // "Blick Doyle and Wuckert",
        // "Grant Dooley and Turcotte",
        // "Graham Grimes and Johns",
        // "Nicolas and Sons",
        // "Dooley-Homenick",
        // "Lebsack LLC",
        // "Dibbert-Zieme",
        // "Jakubowski-Fritsch",
        // "Schaefer Group",
        // "Cremin-Paucek",
        // "Klein LLC",
        // "Ziemann and Sons",
        // "Roob Howe and Champlin",
        // "Collins Gusikowski and Kuhlman",
        // "Lockman Kohler and Hegmann",
        // "Volkman Group",
        // "Stiedemann Swift and Sauer",
        // "Abbott Ltd",
        // "Schaefer-Kshlerin",
        // "Purdy Bergnaum and Torphy",
        // "Robel-O'Kon",
        // "Robel PLC",
        // "Hartmann Cormier and Hermiston",
        // "Feil LLC",
        // "Rosenbaum Senger and Goldner",
    ];

    public static function getBrand(): string
    {
        return Arr::random(self::$brands);
    }
}
